#!/usr/bin/env python3
"""
Custom Oracle -> PostgreSQL migrator and converter.

This is intentionally not Ora2Pg. It uses:
  - python-oracledb to read Oracle metadata and table data
  - psycopg 3 to create PostgreSQL objects and stream data with COPY

Generated object support:
  - tables
  - table data
  - views
  - indexes
  - foreign keys
  - simple synonym replacements as PostgreSQL views
  - basic range/list/hash partition DDL
  - best-effort PL/SQL procedure/function/package/trigger conversion files

Important limitation:
  PL/SQL packages, triggers, and complex procedures are not 1:1 compatible with PostgreSQL.
  This script writes converted PL/pgSQL to reviewable SQL files by default.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

import oracledb
import psycopg
from psycopg import sql


# -----------------------------------------------------------------------------
# Naming and type helpers
# -----------------------------------------------------------------------------


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_name(name: str, preserve_case: bool = False) -> str:
    return name if preserve_case else name.lower()


def read_lob(value: Any) -> Any:
    if value is None:
        return None
    if hasattr(value, "read"):
        return value.read()
    return value


def normalize_copy_value(value: Any) -> Any:
    return read_lob(value)


def map_oracle_type_to_postgres(col: dict[str, Any] | str) -> str:
    if isinstance(col, str):
        data_type = col.upper()
        precision = None
        scale = None
        char_len = None
        identity = False
    else:
        data_type = str(col.get("DATA_TYPE") or col.get("data_type") or "").upper()
        precision = col.get("DATA_PRECISION") or col.get("data_precision")
        scale = col.get("DATA_SCALE") or col.get("data_scale")
        char_len = (
            col.get("CHAR_COL_DECL_LENGTH")
            or col.get("char_col_decl_length")
            or col.get("DATA_LENGTH")
            or col.get("data_length")
        )
        identity = str(col.get("IDENTITY_COLUMN") or "NO").upper() == "YES"

    if identity:
        return "bigint GENERATED BY DEFAULT AS IDENTITY"

    if data_type in {"VARCHAR2", "NVARCHAR2", "VARCHAR"}:
        return f"varchar({char_len})" if char_len else "text"
    if data_type in {"CHAR", "NCHAR"}:
        return f"char({char_len})" if char_len else "char"
    if data_type in {"CLOB", "NCLOB", "LONG"}:
        return "text"
    if data_type in {"BLOB", "RAW", "LONG RAW"}:
        return "bytea"
    if data_type == "DATE":
        return "timestamp(0)"
    if data_type.startswith("TIMESTAMP WITH TIME ZONE"):
        return "timestamp with time zone"
    if data_type.startswith("TIMESTAMP WITH LOCAL TIME ZONE"):
        return "timestamp with time zone"
    if data_type.startswith("TIMESTAMP"):
        return "timestamp"
    if data_type == "BINARY_FLOAT":
        return "real"
    if data_type in {"BINARY_DOUBLE", "FLOAT"}:
        return "double precision"
    if data_type in {"PLS_INTEGER", "BINARY_INTEGER"}:
        return "integer"
    if data_type == "BOOLEAN":
        return "boolean"
    if data_type in {"NUMBER", "DECIMAL", "NUMERIC", "INTEGER"}:
        if precision is None and scale is None:
            return "numeric"
        if scale in (None, 0):
            if precision is not None:
                try:
                    p = int(precision)
                    if p <= 4:
                        return "smallint"
                    if p <= 9:
                        return "integer"
                    if p <= 18:
                        return "bigint"
                except Exception:
                    pass
            return "numeric"
        if precision is not None and scale is not None:
            return f"numeric({precision},{scale})"
        return "numeric"
    if data_type == "XMLTYPE":
        return "xml"
    return "text"


# -----------------------------------------------------------------------------
# SQL and PL/SQL conversion helpers
# -----------------------------------------------------------------------------


def strip_oracle_schema_prefix(sql_text: str, oracle_schema: str, preserve_case: bool) -> str:
    schema = re.escape(oracle_schema)
    replacement = pg_name(oracle_schema, preserve_case) + "."
    return re.sub(rf'"?{schema}"?\.', replacement, sql_text, flags=re.IGNORECASE)


def convert_oracle_expression(expr: str, oracle_schema: str = "", preserve_case: bool = False) -> str:
    """Best-effort Oracle SQL expression conversion."""
    if expr is None:
        return ""

    s = str(read_lob(expr)).strip()

    s = re.sub(r"\bEDITIONABLE\b", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\bNONEDITIONABLE\b", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\bFORCE\b", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\bNO FORCE\b", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\bFROM\s+DUAL\b", "", s, flags=re.IGNORECASE)

    replacements = [
        (r"\bSYSDATE\b", "CURRENT_TIMESTAMP"),
        (r"\bSYSTIMESTAMP\b", "CURRENT_TIMESTAMP"),
        (r"\bNVL\s*\(", "COALESCE("),
        (r"\bLENGTHB\s*\(", "length("),
        (r"\bSUBSTR\s*\(", "substring("),
        (r"\bINSTR\s*\(", "strpos("),
        (r"\bREGEXP_LIKE\s*\(([^,]+),\s*([^\)]+)\)", r"(\1 ~ \2)"),
    ]
    for pat, repl in replacements:
        s = re.sub(pat, repl, s, flags=re.IGNORECASE)

    s = re.sub(
        r"TO_DATE\s*\(\s*'([^']+)'\s*,\s*'[^']+'\s*\)",
        lambda m: "DATE '" + m.group(1).strip().split()[0] + "'",
        s,
        flags=re.IGNORECASE,
    )
    s = re.sub(
        r"TO_TIMESTAMP\s*\(\s*'([^']+)'\s*,\s*'[^']+'\s*\)",
        lambda m: "TIMESTAMP '" + m.group(1).strip() + "'",
        s,
        flags=re.IGNORECASE,
    )

    if "(+)" in s:
        s += "\n-- TODO: Oracle outer join operator (+) must be rewritten as LEFT/RIGHT JOIN."
    if re.search(r"\bDECODE\s*\(", s, flags=re.IGNORECASE):
        s += "\n-- TODO: DECODE() should be rewritten as CASE."
    if re.search(r"\bCONNECT\s+BY\b", s, flags=re.IGNORECASE):
        s += "\n-- TODO: CONNECT BY should be rewritten as WITH RECURSIVE."
    if re.search(r"\bPIVOT\b", s, flags=re.IGNORECASE):
        s += "\n-- TODO: Oracle PIVOT needs manual PostgreSQL rewrite."

    if oracle_schema:
        s = strip_oracle_schema_prefix(s, oracle_schema, preserve_case)

    return s


def convert_plsql_body(body: str, oracle_schema: str = "", preserve_case: bool = False) -> str:
    """Best-effort PL/SQL body conversion to PL/pgSQL-like code."""
    s = str(read_lob(body) or "")

    s = re.sub(r":NEW\.([A-Za-z0-9_$#]+)", r"NEW.\1", s, flags=re.IGNORECASE)
    s = re.sub(r":OLD\.([A-Za-z0-9_$#]+)", r"OLD.\1", s, flags=re.IGNORECASE)

    replacements = [
        (r"\bNVL\s*\(", "COALESCE("),
        (r"\bSYSDATE\b", "CURRENT_TIMESTAMP"),
        (r"\bSYSTIMESTAMP\b", "CURRENT_TIMESTAMP"),
        (r"\bTRUE\b", "TRUE"),
        (r"\bFALSE\b", "FALSE"),
    ]
    for pat, repl in replacements:
        s = re.sub(pat, repl, s, flags=re.IGNORECASE)

    # SQL%ROWCOUNT has no direct inline equivalent.
    s = re.sub(
        r"\bSQL%ROWCOUNT\b",
        "/* TODO: replace SQL%ROWCOUNT with GET DIAGNOSTICS var = ROW_COUNT */ 0",
        s,
        flags=re.IGNORECASE,
    )

    # RAISE_APPLICATION_ERROR(-20001, 'msg') -> RAISE EXCEPTION 'msg'
    s = re.sub(
        r"RAISE_APPLICATION_ERROR\s*\(\s*-?\d+\s*,\s*'([^']*)'\s*\)\s*;",
        r"RAISE EXCEPTION '\1';",
        s,
        flags=re.IGNORECASE,
    )

    s = re.sub(r"\n/\s*$", "", s.strip())

    if oracle_schema:
        s = strip_oracle_schema_prefix(s, oracle_schema, preserve_case)

    return s


def comment_block(text: str) -> str:
    return "\n".join("-- " + line for line in str(text).splitlines())


def split_package_subprograms(package_body_source: str) -> list[str]:
    """
    Simple package body splitter.
    It handles many normal package bodies, but nested routines can confuse it.
    """
    src = str(read_lob(package_body_source) or "")
    blocks: list[str] = []
    pattern = re.compile(
        r"\b(PROCEDURE|FUNCTION)\s+([A-Za-z0-9_$#]+)\b.*?\bEND\s+\2\s*;",
        flags=re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(src):
        blocks.append(match.group(0))
    return blocks


def convert_routine_block(
    source: str,
    schema: str,
    routine_name: str | None = None,
    package_name: str | None = None,
    oracle_schema: str = "",
    preserve_case: bool = False,
) -> str:
    """Convert a PL/SQL procedure/function block into reviewable PL/pgSQL."""
    src = str(read_lob(source) or "").strip().rstrip("/").strip()
    src = convert_plsql_body(src, oracle_schema, preserve_case)

    header_match = re.search(
        r"\b(CREATE\s+OR\s+REPLACE\s+)?(EDITIONABLE\s+|NONEDITIONABLE\s+)?(PROCEDURE|FUNCTION)\s+([A-Za-z0-9_$#]+)",
        src,
        flags=re.IGNORECASE,
    )

    if not header_match:
        name = routine_name or "unknown_routine"
        return (
            f"-- TODO: Could not parse routine header for {name}. Manual conversion required.\n"
            f"-- Original source follows:\n"
            + comment_block(src)
            + "\n"
        )

    kind = header_match.group(3).upper()
    original_name = routine_name or header_match.group(4)
    final_name = pg_name(original_name, preserve_case)
    if package_name:
        final_name = pg_name(package_name, preserve_case) + "__" + final_name

    body_match = re.search(r"\b(IS|AS)\b(.*)$", src, flags=re.IGNORECASE | re.DOTALL)
    body_part = body_match.group(2).strip() if body_match else src
    body_part = re.sub(r"\bEND\s+[A-Za-z0-9_$#]+\s*;\s*$", "END;", body_part, flags=re.IGNORECASE | re.DOTALL)

    if not re.search(r"\bBEGIN\b", body_part, flags=re.IGNORECASE):
        body_part = "BEGIN\n    -- TODO: Add converted routine statements here.\nEND;"

    if kind == "FUNCTION":
        return_type = "text"
        ret = re.search(r"\bRETURN\s+([A-Za-z0-9_$.%]+)", src, flags=re.IGNORECASE)
        if ret:
            return_type = map_oracle_type_to_postgres(ret.group(1).split(".")[-1])

        return (
            f"CREATE OR REPLACE FUNCTION {quote_ident(schema)}.{quote_ident(final_name)}()\n"
            f"RETURNS {return_type}\n"
            f"LANGUAGE plpgsql\n"
            f"AS $$\n"
            f"{body_part}\n"
            f"$$;\n"
            f"-- TODO: Review parameters, return type, exceptions, cursors, package state, and transaction behavior.\n"
        )

    return (
        f"CREATE OR REPLACE PROCEDURE {quote_ident(schema)}.{quote_ident(final_name)}()\n"
        f"LANGUAGE plpgsql\n"
        f"AS $$\n"
        f"{body_part}\n"
        f"$$;\n"
        f"-- TODO: Review parameters, exceptions, cursors, package state, and transaction behavior.\n"
    )


# -----------------------------------------------------------------------------
# Oracle metadata fetchers
# -----------------------------------------------------------------------------


def dict_rows(cursor) -> list[dict[str, Any]]:
    names = [d[0] for d in cursor.description]
    return [dict(zip(names, row)) for row in cursor.fetchall()]


def fetch_tables(ora_conn, owner: str, selected_tables: list[str] | None) -> list[str]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT table_name
            FROM all_tables
            WHERE owner = :owner
              AND nested = 'NO'
              AND secondary = 'N'
              AND dropped = 'NO'
            ORDER BY table_name
            """,
            owner=owner,
        )
        tables = [row[0] for row in cur.fetchall()]
    if selected_tables:
        wanted = {t.upper() for t in selected_tables}
        tables = [t for t in tables if t.upper() in wanted]
    return tables


def fetch_columns(ora_conn, owner: str, table: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                column_id,
                column_name,
                data_type,
                data_precision,
                data_scale,
                char_col_decl_length,
                data_length,
                nullable,
                identity_column
            FROM all_tab_columns
            WHERE owner = :owner
              AND table_name = :table_name
            ORDER BY column_id
            """,
            owner=owner,
            table_name=table,
        )
        return dict_rows(cur)


def fetch_primary_key_columns(ora_conn, owner: str, table: str) -> list[str]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT cols.column_name
            FROM all_constraints cons
            JOIN all_cons_columns cols
              ON cons.owner = cols.owner
             AND cons.constraint_name = cols.constraint_name
             AND cons.table_name = cols.table_name
            WHERE cons.owner = :owner
              AND cons.table_name = :table_name
              AND cons.constraint_type = 'P'
            ORDER BY cols.position
            """,
            owner=owner,
            table_name=table,
        )
        return [row[0] for row in cur.fetchall()]


def fetch_partition_info(ora_conn, owner: str, table: str) -> dict[str, Any] | None:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT partitioning_type, subpartitioning_type, partition_count
            FROM all_part_tables
            WHERE owner = :owner AND table_name = :table_name
            """,
            owner=owner,
            table_name=table,
        )
        row = cur.fetchone()
        if not row:
            return None
        info = {
            "partitioning_type": row[0],
            "subpartitioning_type": row[1],
            "partition_count": row[2],
        }

    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name
            FROM all_part_key_columns
            WHERE owner = :owner AND name = :table_name AND object_type = 'TABLE'
            ORDER BY column_position
            """,
            owner=owner,
            table_name=table,
        )
        info["key_columns"] = [row[0] for row in cur.fetchall()]

    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT partition_name, partition_position, high_value
            FROM all_tab_partitions
            WHERE table_owner = :owner AND table_name = :table_name
            ORDER BY partition_position
            """,
            owner=owner,
            table_name=table,
        )
        parts = []
        for name, position, high_value in cur.fetchall():
            parts.append({"partition_name": name, "partition_position": position, "high_value": read_lob(high_value)})
        info["partitions"] = parts

    return info


def fetch_foreign_keys(ora_conn, owner: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                c.constraint_name,
                c.table_name,
                c.r_constraint_name,
                c.delete_rule,
                r.table_name AS ref_table_name,
                cc.column_name,
                cc.position,
                rcc.column_name AS ref_column_name
            FROM all_constraints c
            JOIN all_constraints r
              ON r.owner = c.r_owner
             AND r.constraint_name = c.r_constraint_name
            JOIN all_cons_columns cc
              ON cc.owner = c.owner
             AND cc.constraint_name = c.constraint_name
             AND cc.table_name = c.table_name
            JOIN all_cons_columns rcc
              ON rcc.owner = r.owner
             AND rcc.constraint_name = r.constraint_name
             AND rcc.position = cc.position
            WHERE c.owner = :owner
              AND c.constraint_type = 'R'
            ORDER BY c.table_name, c.constraint_name, cc.position
            """,
            owner=owner,
        )
        return dict_rows(cur)


def fetch_indexes(ora_conn, owner: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                i.index_name,
                i.table_name,
                i.uniqueness,
                i.index_type,
                i.generated,
                i.status,
                ic.column_name,
                ic.column_position,
                ic.descend
            FROM all_indexes i
            JOIN all_ind_columns ic
              ON ic.index_owner = i.owner
             AND ic.index_name = i.index_name
            WHERE i.owner = :owner
              AND i.index_type NOT LIKE 'LOB%'
            ORDER BY i.table_name, i.index_name, ic.column_position
            """,
            owner=owner,
        )
        rows = dict_rows(cur)

    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT index_name
            FROM all_constraints
            WHERE owner = :owner
              AND constraint_type IN ('P','U')
              AND index_name IS NOT NULL
            """,
            owner=owner,
        )
        constraint_indexes = {row[0] for row in cur.fetchall()}

    return [r for r in rows if r["INDEX_NAME"] not in constraint_indexes]


def fetch_views(ora_conn, owner: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT view_name, text
            FROM all_views
            WHERE owner = :owner
            ORDER BY view_name
            """,
            owner=owner,
        )
        rows = []
        for view_name, text in cur.fetchall():
            rows.append({"VIEW_NAME": view_name, "TEXT": read_lob(text)})
        return rows


def fetch_synonyms(ora_conn, owner: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT synonym_name, table_owner, table_name, db_link
            FROM all_synonyms
            WHERE owner = :owner
            ORDER BY synonym_name
            """,
            owner=owner,
        )
        return dict_rows(cur)


def fetch_triggers(ora_conn, owner: str) -> list[dict[str, Any]]:
    with ora_conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                trigger_name,
                table_name,
                trigger_type,
                triggering_event,
                when_clause,
                trigger_body,
                status
            FROM all_triggers
            WHERE owner = :owner
            ORDER BY trigger_name
            """,
            owner=owner,
        )
        rows = []
        for row in cur.fetchall():
            rows.append(
                {
                    "TRIGGER_NAME": row[0],
                    "TABLE_NAME": row[1],
                    "TRIGGER_TYPE": row[2],
                    "TRIGGERING_EVENT": row[3],
                    "WHEN_CLAUSE": read_lob(row[4]),
                    "TRIGGER_BODY": read_lob(row[5]),
                    "STATUS": row[6],
                }
            )
        return rows


def fetch_source_grouped(ora_conn, owner: str, object_types: Iterable[str]) -> dict[tuple[str, str], str]:
    types = [t.upper() for t in object_types]
    binds = ",".join(f":t{i}" for i in range(len(types)))
    params = {"owner": owner, **{f"t{i}": t for i, t in enumerate(types)}}
    with ora_conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT type, name, line, text
            FROM all_source
            WHERE owner = :owner
              AND type IN ({binds})
            ORDER BY type, name, line
            """,
            params,
        )
        grouped: dict[tuple[str, str], list[str]] = defaultdict(list)
        for typ, name, _line, text in cur.fetchall():
            grouped[(typ, name)].append(text)
    return {key: "".join(lines) for key, lines in grouped.items()}


# -----------------------------------------------------------------------------
# PostgreSQL DDL generators
# -----------------------------------------------------------------------------


def create_schema_sql(pg_schema: str) -> str:
    return f"CREATE SCHEMA IF NOT EXISTS {quote_ident(pg_schema)};\n"


def table_ddl_sql(
    ora_conn,
    owner: str,
    table: str,
    pg_schema: str,
    preserve_case: bool,
    convert_partitions: bool,
) -> list[str]:
    columns = fetch_columns(ora_conn, owner, table)
    pk_cols = fetch_primary_key_columns(ora_conn, owner, table)
    pg_table = pg_name(table, preserve_case)

    column_defs: list[str] = []
    for col in columns:
        source_col = col["COLUMN_NAME"]
        target_col = pg_name(source_col, preserve_case)
        pg_type = map_oracle_type_to_postgres(col)
        nullable = str(col["NULLABLE"]).upper() == "Y"
        not_null = "" if nullable else " NOT NULL"
        column_defs.append(f"    {quote_ident(target_col)} {pg_type}{not_null}")

    if pk_cols:
        pg_pk_cols = [quote_ident(pg_name(c, preserve_case)) for c in pk_cols]
        column_defs.append(f"    PRIMARY KEY ({', '.join(pg_pk_cols)})")

    partition_info = fetch_partition_info(ora_conn, owner, table) if convert_partitions else None
    partition_clause = ""
    partition_ddls: list[str] = []

    if partition_info:
        ptype = str(partition_info["partitioning_type"]).upper()
        key_cols = [quote_ident(pg_name(c, preserve_case)) for c in partition_info.get("key_columns", [])]
        if key_cols and ptype in {"RANGE", "LIST", "HASH"}:
            partition_clause = f" PARTITION BY {ptype} ({', '.join(key_cols)})"
            partition_ddls = partition_ddl_sql(partition_info, pg_schema, pg_table, preserve_case)
        else:
            partition_ddls.append(f"-- TODO: Unsupported partition type/key for {table}: {partition_info}\n")

    ddl = (
        f"CREATE TABLE {quote_ident(pg_schema)}.{quote_ident(pg_table)} (\n"
        + ",\n".join(column_defs)
        + f"\n){partition_clause};\n"
    )
    return [ddl] + partition_ddls


def partition_ddl_sql(info: dict[str, Any], pg_schema: str, pg_table: str, preserve_case: bool) -> list[str]:
    ptype = str(info["partitioning_type"]).upper()
    parts = info.get("partitions", [])
    ddls: list[str] = []

    if ptype == "RANGE":
        previous = "MINVALUE"
        for part in parts:
            part_name = pg_name(part["partition_name"], preserve_case)
            high = convert_partition_bound(part.get("high_value"))
            to_value = "MAXVALUE" if high.upper() == "MAXVALUE" else high
            ddls.append(
                f"CREATE TABLE {quote_ident(pg_schema)}.{quote_ident(pg_table + '_' + part_name)} "
                f"PARTITION OF {quote_ident(pg_schema)}.{quote_ident(pg_table)} "
                f"FOR VALUES FROM ({previous}) TO ({to_value});\n"
            )
            previous = to_value
        return ddls

    if ptype == "LIST":
        for part in parts:
            part_name = pg_name(part["partition_name"], preserve_case)
            high = convert_partition_bound(part.get("high_value"))
            ddls.append(
                f"CREATE TABLE {quote_ident(pg_schema)}.{quote_ident(pg_table + '_' + part_name)} "
                f"PARTITION OF {quote_ident(pg_schema)}.{quote_ident(pg_table)} "
                f"FOR VALUES IN ({high});\n"
            )
        return ddls

    if ptype == "HASH":
        modulus = max(len(parts), 1)
        for i, part in enumerate(parts):
            part_name = pg_name(part["partition_name"], preserve_case)
            ddls.append(
                f"CREATE TABLE {quote_ident(pg_schema)}.{quote_ident(pg_table + '_' + part_name)} "
                f"PARTITION OF {quote_ident(pg_schema)}.{quote_ident(pg_table)} "
                f"FOR VALUES WITH (MODULUS {modulus}, REMAINDER {i});\n"
            )
        return ddls

    return [f"-- TODO: Unsupported partitioning type: {ptype}\n"]


def convert_partition_bound(value: Any) -> str:
    s = str(read_lob(value) or "").strip()
    return convert_oracle_expression(s)


def foreign_key_sql(rows: list[dict[str, Any]], pg_schema: str, preserve_case: bool) -> list[str]:
    grouped: dict[tuple[str, str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        key = (r["TABLE_NAME"], r["CONSTRAINT_NAME"], r["REF_TABLE_NAME"], r["DELETE_RULE"])
        grouped[key].append(r)

    ddls: list[str] = []
    for (table, cname, ref_table, delete_rule), cols in grouped.items():
        cols = sorted(cols, key=lambda r: r["POSITION"])
        local_cols = ", ".join(quote_ident(pg_name(r["COLUMN_NAME"], preserve_case)) for r in cols)
        ref_cols = ", ".join(quote_ident(pg_name(r["REF_COLUMN_NAME"], preserve_case)) for r in cols)
        on_delete = ""
        if delete_rule and str(delete_rule).upper() not in {"NO ACTION", "RESTRICT"}:
            on_delete = f" ON DELETE {str(delete_rule).upper()}"
        ddls.append(
            f"ALTER TABLE {quote_ident(pg_schema)}.{quote_ident(pg_name(table, preserve_case))} "
            f"ADD CONSTRAINT {quote_ident(pg_name(cname, preserve_case))} "
            f"FOREIGN KEY ({local_cols}) "
            f"REFERENCES {quote_ident(pg_schema)}.{quote_ident(pg_name(ref_table, preserve_case))} ({ref_cols})"
            f"{on_delete};\n"
        )
    return ddls


def index_sql(rows: list[dict[str, Any]], pg_schema: str, preserve_case: bool) -> list[str]:
    grouped: dict[tuple[str, str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        key = (r["TABLE_NAME"], r["INDEX_NAME"], r["UNIQUENESS"], r["INDEX_TYPE"])
        grouped[key].append(r)

    ddls: list[str] = []
    for (table, idx, uniqueness, index_type), cols in grouped.items():
        cols = sorted(cols, key=lambda r: r["COLUMN_POSITION"])
        pg_cols = []
        for r in cols:
            col = quote_ident(pg_name(r["COLUMN_NAME"], preserve_case))
            if str(r.get("DESCEND") or "ASC").upper() == "DESC":
                col += " DESC"
            pg_cols.append(col)

        unique = "UNIQUE " if str(uniqueness).upper() == "UNIQUE" else ""
        note = ""
        if "BITMAP" in str(index_type).upper():
            note = "-- Oracle BITMAP index converted to normal PostgreSQL btree index. Review manually.\n"
        elif "FUNCTION" in str(index_type).upper():
            note = "-- TODO: Function-based index may need manual expression conversion.\n"

        ddls.append(
            note
            + f"CREATE {unique}INDEX {quote_ident(pg_name(idx, preserve_case))} "
            + f"ON {quote_ident(pg_schema)}.{quote_ident(pg_name(table, preserve_case))} "
            + f"({', '.join(pg_cols)});\n"
        )
    return ddls


def view_sql(rows: list[dict[str, Any]], pg_schema: str, oracle_schema: str, preserve_case: bool) -> list[str]:
    ddls: list[str] = []
    for r in rows:
        name = pg_name(r["VIEW_NAME"], preserve_case)
        body = convert_oracle_expression(r["TEXT"], oracle_schema, preserve_case)
        ddls.append(
            f"CREATE OR REPLACE VIEW {quote_ident(pg_schema)}.{quote_ident(name)} AS\n"
            f"{body}\n;\n"
            f"-- TODO: Review Oracle-specific functions, DECODE(), CONNECT BY, MODEL, PIVOT, and outer joins.\n"
        )
    return ddls


def synonym_sql(rows: list[dict[str, Any]], pg_schema: str, preserve_case: bool) -> list[str]:
    ddls: list[str] = []
    for r in rows:
        synonym = pg_name(r["SYNONYM_NAME"], preserve_case)
        target_schema = pg_name(r["TABLE_OWNER"], preserve_case)
        target_name = pg_name(r["TABLE_NAME"], preserve_case)
        db_link = r.get("DB_LINK")

        if db_link:
            ddls.append(
                f"-- TODO: Synonym {synonym} points through Oracle DB_LINK {db_link}; "
                f"PostgreSQL needs postgres_fdw, dblink, or manual replacement.\n"
            )
            continue

        ddls.append(
            f"CREATE OR REPLACE VIEW {quote_ident(pg_schema)}.{quote_ident(synonym)} AS\n"
            f"SELECT * FROM {quote_ident(target_schema)}.{quote_ident(target_name)};\n"
            f"-- Synonym replacement: Oracle synonym {synonym} -> view over {target_schema}.{target_name}.\n"
        )
    return ddls


def trigger_sql(rows: list[dict[str, Any]], pg_schema: str, oracle_schema: str, preserve_case: bool) -> list[str]:
    ddls: list[str] = []
    for r in rows:
        trg = pg_name(r["TRIGGER_NAME"], preserve_case)
        table = pg_name(r["TABLE_NAME"], preserve_case)
        fn = f"{trg}_fn"
        trigger_type = str(r["TRIGGER_TYPE"] or "").upper()
        triggering_event = str(r["TRIGGERING_EVENT"] or "").upper()
        body = convert_plsql_body(r["TRIGGER_BODY"], oracle_schema, preserve_case)

        timing = "BEFORE"
        if "AFTER" in trigger_type:
            timing = "AFTER"
        elif "INSTEAD OF" in trigger_type:
            timing = "INSTEAD OF"

        level = "FOR EACH ROW" if "EACH ROW" in trigger_type else "FOR EACH STATEMENT"
        events = " OR ".join(e.strip() for e in triggering_event.split(" OR ") if e.strip())
        events = events or "INSERT OR UPDATE OR DELETE"

        when_clause = ""
        if r.get("WHEN_CLAUSE"):
            when_expr = convert_plsql_body(r["WHEN_CLAUSE"], oracle_schema, preserve_case)
            when_clause = f"WHEN ({when_expr})\n"

        return_stmt = "RETURN NEW;"
        if "DELETE" in triggering_event and "INSERT" not in triggering_event and "UPDATE" not in triggering_event:
            return_stmt = "RETURN OLD;"
        if "STATEMENT" in level:
            return_stmt = "RETURN NULL;"

        ddls.append(
            f"CREATE OR REPLACE FUNCTION {quote_ident(pg_schema)}.{quote_ident(fn)}()\n"
            f"RETURNS trigger\n"
            f"LANGUAGE plpgsql\n"
            f"AS $$\n"
            f"BEGIN\n"
            f"{body}\n"
            f"    {return_stmt}\n"
            f"END;\n"
            f"$$;\n\n"
            f"DROP TRIGGER IF EXISTS {quote_ident(trg)} ON {quote_ident(pg_schema)}.{quote_ident(table)};\n"
            f"CREATE TRIGGER {quote_ident(trg)}\n"
            f"{timing} {events} ON {quote_ident(pg_schema)}.{quote_ident(table)}\n"
            f"{level}\n"
            f"{when_clause}"
            f"EXECUTE FUNCTION {quote_ident(pg_schema)}.{quote_ident(fn)}();\n"
            f"-- TODO: Review trigger transition variables, mutating-table logic, WHEN clause, autonomous transactions, and statement-level behavior.\n"
        )
    return ddls


def routine_sql(source_map: dict[tuple[str, str], str], pg_schema: str, oracle_schema: str, preserve_case: bool) -> list[str]:
    ddls: list[str] = []
    for (typ, name), source in sorted(source_map.items()):
        if typ in {"PROCEDURE", "FUNCTION"}:
            ddls.append(convert_routine_block(source, schema=pg_schema, routine_name=name, oracle_schema=oracle_schema, preserve_case=preserve_case))
    return ddls


def package_sql(source_map: dict[tuple[str, str], str], pg_schema: str, oracle_schema: str, preserve_case: bool) -> list[str]:
    ddls: list[str] = []
    for (typ, package_name), source in sorted(source_map.items()):
        if typ != "PACKAGE BODY":
            continue
        blocks = split_package_subprograms(source)
        if not blocks:
            ddls.append(f"-- TODO: Could not split package body {package_name}. Manual conversion required.\n" + comment_block(source) + "\n")
            continue
        ddls.append(f"-- Package {package_name} converted into standalone routines named package__routine.\n")
        ddls.append("-- TODO: PostgreSQL has no Oracle-style package state. Package variables/constants/types must be redesigned manually.\n")
        for block in blocks:
            name_match = re.search(r"\b(PROCEDURE|FUNCTION)\s+([A-Za-z0-9_$#]+)", block, flags=re.IGNORECASE)
            routine_name = name_match.group(2) if name_match else None
            ddls.append(convert_routine_block(block, schema=pg_schema, routine_name=routine_name, package_name=package_name, oracle_schema=oracle_schema, preserve_case=preserve_case))
    return ddls


# -----------------------------------------------------------------------------
# Apply/export layer
# -----------------------------------------------------------------------------


def split_sql_statements(sql_text: str) -> list[str]:
    """
    Simple splitter that keeps dollar-quoted function bodies intact.
    Good enough for generated SQL from this script.
    """
    statements = []
    buf = []
    in_dollar = False
    i = 0
    while i < len(sql_text):
        if sql_text.startswith("$$", i):
            in_dollar = not in_dollar
            buf.append("$$")
            i += 2
            continue
        ch = sql_text[i]
        buf.append(ch)
        if ch == ";" and not in_dollar:
            statements.append("".join(buf).strip())
            buf = []
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements


def execute_sql_batch(pg_conn, sql_text: str, stop_on_error: bool) -> None:
    statements = split_sql_statements(sql_text)
    with pg_conn.cursor() as cur:
        for stmt in statements:
            if not stmt.strip():
                continue
            try:
                cur.execute(stmt)
            except Exception as exc:
                pg_conn.rollback()
                print("\nFAILED SQL:\n" + stmt[:2000], file=sys.stderr)
                print(f"ERROR: {exc}", file=sys.stderr)
                if stop_on_error:
                    raise
    pg_conn.commit()


def write_sql_file(out_dir: Path, filename: str, statements: Iterable[str]) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / filename
    with path.open("w", encoding="utf-8") as f:
        for stmt in statements:
            f.write(stmt)
            if not stmt.endswith("\n"):
                f.write("\n")
            f.write("\n")
    return path


def copy_table_data(ora_conn, pg_conn, owner: str, table: str, pg_schema: str, preserve_case: bool, batch_size: int) -> int:
    columns = fetch_columns(ora_conn, owner, table)
    source_columns = [c["COLUMN_NAME"] for c in columns]
    target_columns = [pg_name(c, preserve_case) for c in source_columns]
    pg_table = pg_name(table, preserve_case)

    oracle_select_columns = ", ".join(quote_ident(c) for c in source_columns)
    oracle_sql = f"SELECT {oracle_select_columns} FROM {quote_ident(owner)}.{quote_ident(table)}"

    copied = 0
    with ora_conn.cursor() as ora_cur:
        ora_cur.arraysize = batch_size
        ora_cur.execute(oracle_sql)
        with pg_conn.cursor() as pg_cur:
            copy_sql = sql.SQL("COPY {}.{} ({}) FROM STDIN").format(
                sql.Identifier(pg_schema),
                sql.Identifier(pg_table),
                sql.SQL(", ").join(sql.Identifier(c) for c in target_columns),
            )
            with pg_cur.copy(copy_sql) as copy:
                while True:
                    rows = ora_cur.fetchmany(batch_size)
                    if not rows:
                        break
                    for row in rows:
                        copy.write_row([normalize_copy_value(v) for v in row])
                        copied += 1
    return copied


def generate_all_sql(args, ora_conn) -> dict[str, str]:
    owner = args.oracle_schema.upper()
    pg_schema = args.pg_schema
    preserve_case = args.preserve_case
    tables = fetch_tables(ora_conn, owner, args.tables)

    files: dict[str, list[str]] = {
        "01_schema_tables.sql": [create_schema_sql(pg_schema)],
        "02_views.sql": [],
        "03_indexes.sql": [],
        "04_foreign_keys.sql": [],
        "05_synonyms_as_views.sql": [],
        "06_triggers_review.sql": [],
        "07_routines_review.sql": [],
        "08_packages_review.sql": [],
    }

    for table in tables:
        if args.drop_existing:
            files["01_schema_tables.sql"].append(f"DROP TABLE IF EXISTS {quote_ident(pg_schema)}.{quote_ident(pg_name(table, preserve_case))} CASCADE;\n")
        files["01_schema_tables.sql"].extend(table_ddl_sql(ora_conn, owner, table, pg_schema, preserve_case, convert_partitions=args.convert_partitions))

    if args.convert_views:
        files["02_views.sql"].extend(view_sql(fetch_views(ora_conn, owner), pg_schema, owner, preserve_case))
    if args.convert_indexes:
        files["03_indexes.sql"].extend(index_sql(fetch_indexes(ora_conn, owner), pg_schema, preserve_case))
    if args.convert_foreign_keys:
        files["04_foreign_keys.sql"].extend(foreign_key_sql(fetch_foreign_keys(ora_conn, owner), pg_schema, preserve_case))
    if args.convert_synonyms:
        files["05_synonyms_as_views.sql"].extend(synonym_sql(fetch_synonyms(ora_conn, owner), pg_schema, preserve_case))
    if args.convert_triggers:
        files["06_triggers_review.sql"].extend(trigger_sql(fetch_triggers(ora_conn, owner), pg_schema, owner, preserve_case))
    if args.convert_routines:
        src = fetch_source_grouped(ora_conn, owner, ["PROCEDURE", "FUNCTION"])
        files["07_routines_review.sql"].extend(routine_sql(src, pg_schema, owner, preserve_case))
    if args.convert_packages:
        src = fetch_source_grouped(ora_conn, owner, ["PACKAGE", "PACKAGE BODY"])
        files["08_packages_review.sql"].extend(package_sql(src, pg_schema, owner, preserve_case))

    output_paths: dict[str, str] = {}
    out_dir = Path(args.out_dir)
    for filename, stmts in files.items():
        if stmts:
            output_paths[filename] = str(write_sql_file(out_dir, filename, stmts))
    return output_paths


def migrate(args) -> None:
    print("Connecting to Oracle...")
    ora_conn = oracledb.connect(user=args.oracle_user, password=args.oracle_password, dsn=args.oracle_dsn)

    pg_conn = None
    if args.pg_dsn:
        print("Connecting to PostgreSQL...")
        pg_conn = psycopg.connect(args.pg_dsn)

    try:
        paths = generate_all_sql(args, ora_conn)
        print("Generated SQL files:")
        for path in paths.values():
            print("  " + path)

        if pg_conn and args.apply_tables:
            print("Applying schema/tables...")
            execute_sql_batch(pg_conn, Path(paths["01_schema_tables.sql"]).read_text(encoding="utf-8"), args.stop_on_error)

        if pg_conn and args.copy_data:
            owner = args.oracle_schema.upper()
            tables = fetch_tables(ora_conn, owner, args.tables)
            for table in tables:
                print(f"Copying data: {owner}.{table}")
                copied = copy_table_data(ora_conn, pg_conn, owner, table, args.pg_schema, args.preserve_case, args.batch_size)
                pg_conn.commit()
                print(f"  {copied} rows")

        if pg_conn and args.apply_post_data_objects:
            for filename in ["02_views.sql", "03_indexes.sql", "04_foreign_keys.sql", "05_synonyms_as_views.sql"]:
                path = paths.get(filename)
                if path:
                    print(f"Applying {filename}...")
                    execute_sql_batch(pg_conn, Path(path).read_text(encoding="utf-8"), args.stop_on_error)

        if pg_conn and args.apply_code:
            print("Applying converted triggers/routines/packages. This may fail and need manual edits.")
            for filename in ["06_triggers_review.sql", "07_routines_review.sql", "08_packages_review.sql"]:
                path = paths.get(filename)
                if path:
                    print(f"Applying {filename}...")
                    execute_sql_batch(pg_conn, Path(path).read_text(encoding="utf-8"), args.stop_on_error)

        print("Done.")

    finally:
        ora_conn.close()
        if pg_conn:
            pg_conn.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Custom Oracle to PostgreSQL migrator/converter")

    parser.add_argument("--oracle-user", required=True)
    parser.add_argument("--oracle-password", required=True)
    parser.add_argument("--oracle-dsn", required=True, help='Example: "localhost:1521/ORCLPDB1"')
    parser.add_argument("--oracle-schema", required=True)

    parser.add_argument("--pg-dsn", help='Example: "postgresql://postgres:pass@localhost:5432/mydb"')
    parser.add_argument("--pg-schema", default="public")

    parser.add_argument("--out-dir", default="./converted_pg_sql")
    parser.add_argument("--tables", nargs="*", help="Optional list of Oracle tables")
    parser.add_argument("--batch-size", type=int, default=5000)

    parser.add_argument("--drop-existing", action="store_true")
    parser.add_argument("--preserve-case", action="store_true")
    parser.add_argument("--stop-on-error", action="store_true")

    parser.add_argument("--convert-partitions", action="store_true")
    parser.add_argument("--convert-views", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-indexes", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-foreign-keys", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-synonyms", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-triggers", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-routines", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--convert-packages", action=argparse.BooleanOptionalAction, default=True)

    parser.add_argument("--apply-tables", action="store_true", help="Execute generated table DDL in PostgreSQL")
    parser.add_argument("--copy-data", action="store_true", help="Copy Oracle table data into PostgreSQL")
    parser.add_argument("--apply-post-data-objects", action="store_true", help="Apply views, indexes, foreign keys, and synonym-replacement views")
    parser.add_argument("--apply-code", action="store_true", help="Apply converted triggers/routines/packages. Usually leave off until reviewed.")

    return parser.parse_args()


if __name__ == "__main__":
    try:
        migrate(parse_args())
    except KeyboardInterrupt:
        print("Cancelled.", file=sys.stderr)
        sys.exit(130)
    except Exception as exc:
        print(f"Migration failed: {exc}", file=sys.stderr)
        sys.exit(1)
