import argparse

import oracle_to_postgres_advanced as mig


def test_quote_ident_escapes_embedded_quotes():
    assert mig.quote_ident('weird"name') == '"weird""name"'


def test_pg_name_lowercases_by_default_and_can_preserve_case():
    assert mig.pg_name("EMPLOYEES") == "employees"
    assert mig.pg_name("EMPLOYEES", preserve_case=True) == "EMPLOYEES"


def test_type_mapping_for_common_oracle_types():
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "VARCHAR2", "DATA_LENGTH": 50}) == "varchar(50)"
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "NUMBER", "DATA_PRECISION": 9, "DATA_SCALE": 0}) == "integer"
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "NUMBER", "DATA_PRECISION": 12, "DATA_SCALE": 2}) == "numeric(12,2)"
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "CLOB"}) == "text"
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "BLOB"}) == "bytea"
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "DATE"}) == "timestamp(0)"


def test_identity_column_maps_to_postgres_identity():
    assert mig.map_oracle_type_to_postgres({"DATA_TYPE": "NUMBER", "IDENTITY_COLUMN": "YES"}) == "bigint GENERATED BY DEFAULT AS IDENTITY"


def test_oracle_expression_conversion_handles_common_functions():
    converted = mig.convert_oracle_expression("SELECT NVL(name, 'x'), SYSDATE FROM dual")
    assert "COALESCE(name, 'x')" in converted
    assert "CURRENT_TIMESTAMP" in converted
    assert "FROM dual" not in converted.lower()


def test_plsql_body_converts_trigger_record_references():
    converted = mig.convert_plsql_body(":NEW.updated_at := SYSDATE; :OLD.id := :OLD.id;")
    assert "NEW.updated_at" in converted
    assert "OLD.id" in converted
    assert "CURRENT_TIMESTAMP" in converted


def test_sql_splitter_keeps_dollar_quoted_function_body_together():
    sql_text = """
    CREATE TABLE t (id integer);
    CREATE OR REPLACE FUNCTION f()
    RETURNS integer
    LANGUAGE plpgsql
    AS $$
    BEGIN
        RETURN 1;
    END;
    $$;
    CREATE INDEX t_id_idx ON t(id);
    """
    statements = mig.split_sql_statements(sql_text)
    assert len(statements) == 3
    assert "RETURN 1;" in statements[1]


def test_foreign_key_sql_groups_columns_in_order():
    rows = [
        {
            "TABLE_NAME": "CHILD",
            "CONSTRAINT_NAME": "FK_CHILD_PARENT",
            "REF_TABLE_NAME": "PARENT",
            "DELETE_RULE": "CASCADE",
            "COLUMN_NAME": "PARENT_ID",
            "REF_COLUMN_NAME": "ID",
            "POSITION": 1,
        }
    ]
    ddl = mig.foreign_key_sql(rows, "public", preserve_case=False)[0]
    assert 'ALTER TABLE "public"."child"' in ddl
    assert 'FOREIGN KEY ("parent_id")' in ddl
    assert 'REFERENCES "public"."parent" ("id")' in ddl
    assert "ON DELETE CASCADE" in ddl


def test_index_sql_generates_basic_btree_index():
    rows = [
        {
            "TABLE_NAME": "EMP",
            "INDEX_NAME": "EMP_NAME_IDX",
            "UNIQUENESS": "NONUNIQUE",
            "INDEX_TYPE": "NORMAL",
            "COLUMN_NAME": "NAME",
            "COLUMN_POSITION": 1,
            "DESCEND": "ASC",
        }
    ]
    ddl = mig.index_sql(rows, "public", preserve_case=False)[0]
    assert 'CREATE INDEX "emp_name_idx" ON "public"."emp" ("name");' in ddl


def test_parser_supports_no_convert_flags(monkeypatch):
    argv = [
        "prog",
        "--oracle-user", "HR",
        "--oracle-password", "secret",
        "--oracle-dsn", "localhost:1521/ORCLPDB1",
        "--oracle-schema", "HR",
        "--no-convert-views",
        "--no-convert-indexes",
    ]
    monkeypatch.setattr("sys.argv", argv)
    args = mig.parse_args()
    assert args.convert_views is False
    assert args.convert_indexes is False
    assert args.convert_foreign_keys is True
